/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public\\img\\models\\lofi_office_optimized.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lofi_office_optimized.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.room.geometry} material={nodes.room.material} />
      <mesh geometry={nodes.couch.geometry} material={nodes.couch.material} position={[-3.03, 0.32, 0.97]} rotation={[0, Math.PI / 2, 0]} scale={0.76}>
        <mesh geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.04, -0.06, -0.07]} rotation={[-Math.PI, 0, 0]} />
        <mesh geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[1.06, 0.38, 0.18]} />
        <mesh geometry={nodes.Plane003.geometry} material={nodes.Plane003.material} position={[-1, 0.38, 0.18]} />
        <mesh geometry={nodes.Plane004_1.geometry} material={nodes.Plane004_1.material} position={[1.79, 1.34, -0.63]} rotation={[1.41, 0, 0]} />
        <mesh geometry={nodes.Plane005_1.geometry} material={nodes.Plane005_1.material} position={[0.03, 1.34, -0.63]} rotation={[1.41, 0, 0]} />
        <mesh geometry={nodes.Plane006_1.geometry} material={nodes.Plane006_1.material} position={[-1.67, 1.34, -0.63]} rotation={[1.41, 0, 0]} />
        <mesh geometry={nodes.Plane007_1.geometry} material={nodes.Plane007_1.material} position={[2.22, 0.89, 0.26]} rotation={[0, 1.57, 0]} />
        <mesh geometry={nodes.Plane008_1.geometry} material={nodes.Plane008_1.material} position={[-2.3, 0.89, 0.26]} rotation={[0, 1.57, 0]} />
      </mesh>
      <mesh geometry={nodes.table.geometry} material={nodes.table.material} position={[0.9, 1.19, -2.85]}>
        <mesh geometry={nodes.Circle_1.geometry} material={nodes.Circle_1.material} position={[-1.65, 0.23, 0.71]} />
        <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[1.63, 0.23, 0.71]} />
        <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[1.63, 0.23, -0.68]} />
        <mesh geometry={nodes.Circle003.geometry} material={nodes.Circle003.material} position={[-1.67, 0.23, -0.68]} />
      </mesh>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.57, 0.15, 1.16]} />
      <mesh geometry={nodes.laptop_base.geometry} material={nodes.laptop_base.material} position={[0.54, 1.42, -3.17]} />
      <mesh geometry={nodes.laptop_screen.geometry} material={nodes.laptop_screen.material} position={[0.54, 1.82, -3.63]} rotation={[1.31, 0, 0]} />
      <mesh geometry={nodes.KEYBOARD.geometry} material={nodes.KEYBOARD.material} position={[0.17, 1.48, -3.3]} scale={[0.03, 0, 0.03]} />
      <mesh geometry={nodes.monitor.geometry} material={nodes.monitor.material} position={[1.89, 2.44, -3.63]} rotation={[Math.PI / 2, 0, 0.26]} />
      <mesh geometry={nodes.monitor_base.geometry} material={nodes.monitor_base.material} position={[1.88, 1.42, -3.68]} rotation={[0, -0.26, 0]} />
      <mesh geometry={nodes.Cube029.geometry} material={nodes.Cube029.material} position={[1.42, 1.49, -3.09]} rotation={[0, 0.76, 0]} />
      <mesh geometry={nodes.Torus.geometry} material={nodes.Torus.material} position={[1.35, 1.5, -3.04]} rotation={[Math.PI / 2, 0, -0.76]} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[1.42, 1.52, -3.09]} />
      <mesh geometry={nodes.Cube054.geometry} material={nodes.Cube054.material} position={[1.01, 0.36, -1.21]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={0.03} />
      <mesh geometry={nodes.Cube063.geometry} material={nodes.Cube063.material} position={[1.01, 0.36, -1.21]} rotation={[Math.PI, -1.3, Math.PI]} scale={0.03} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[1, 0.46, -1.21]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={0.07} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[1, 0.62, -1.21]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={[0.06, 0.05, 0.05]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[1, 0.73, -1.21]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={[0.06, 0.04, 0.04]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[1.01, 0.19, -1.21]} rotation={[Math.PI / 2, 0, -2.87]} scale={0.07} />
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[1.01, 0.19, -1.21]} rotation={[Math.PI / 2, 0, -1.3]} scale={0.07} />
      <mesh geometry={nodes.Cube064.geometry} material={nodes.Cube064.material} position={[1.01, 1.53, -1.29]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={0.54} />
      <mesh geometry={nodes.Cube084.geometry} material={nodes.Cube084.material} position={[0.79, 1.88, -0.5]} rotation={[-Math.PI / 2, 0, 2.87]} scale={0.54} />
      <mesh geometry={nodes.Cube085.geometry} material={nodes.Cube085.material} position={[1, 1.26, -1.27]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={0.07} />
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[0.85, 0.98, -1.25]} rotation={[Math.PI, 0.28, 1.44]} scale={[0.01, 0.17, 0.01]} />
      <mesh geometry={nodes.Icosphere.geometry} material={nodes.Icosphere.material} position={[0.67, 0.95, -1.31]} rotation={[-Math.PI, 0.28, -Math.PI]} scale={-0.03} />
      <mesh geometry={nodes.pot.geometry} material={nodes.pot.material} position={[-2.42, 0.44, -2.36]} />
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} position={[-2.42, 0.98, -1.82]} />
      <mesh geometry={nodes.Plane010.geometry} material={nodes.Plane010.material} position={[-2.42, 0.98, -3.02]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[-1.86, 0.98, -2.39]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} position={[-3.03, 0.98, -2.39]} rotation={[0, -1.57, 0]} />
      <mesh geometry={nodes.window.geometry} material={nodes.window.material} position={[-4.04, 2.98, -0.87]} scale={[0.08, 0.86, 0.73]} />
      <mesh geometry={nodes.window001.geometry} material={nodes.window001.material} position={[-4.02, 2.98, 2.53]} scale={[0.08, 0.86, 0.73]} />
      <mesh geometry={nodes.window003.geometry} material={nodes.window003.material} position={[-1.62, 2.98, -4.04]} rotation={[0, -Math.PI / 2, 0]} scale={[0.08, 0.86, 0.73]} />
    </group>
  )
}

useGLTF.preload('/lofi_office_optimized.glb')
